# Generated by Django 4.1.6 on 2023-03-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_image_delete_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
